/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazgrafica;

/**
 *
 * @author APRENDIZ
 */
public class calculadora extends javax.swing.JFrame {

    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBorrar = new javax.swing.JButton();
        caja3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSumar = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        caja2 = new javax.swing.JTextField();
        btnDividir1 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        btnBorrar.setBackground(new java.awt.Color(255, 0, 102));
        btnBorrar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnBorrar.setText("C");
        btnBorrar.setAlignmentY(0.0F);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrar);
        btnBorrar.setBounds(60, 330, 50, 30);

        caja3.setBackground(new java.awt.Color(255, 255, 255));
        caja3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        caja3.setBorder(null);
        caja3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja3ActionPerformed(evt);
            }
        });
        jPanel1.add(caja3);
        caja3.setBounds(160, 330, 140, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("CALCULADORA");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 20, 259, 48);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Resultado");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(200, 370, 66, 20);

        btnSumar.setBackground(new java.awt.Color(255, 0, 102));
        btnSumar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnSumar.setText("+");
        btnSumar.setAlignmentY(0.0F);
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSumar);
        btnSumar.setBounds(60, 170, 50, 30);

        btnRestar.setBackground(new java.awt.Color(255, 0, 102));
        btnRestar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnRestar.setText("-");
        btnRestar.setAlignmentY(0.0F);
        btnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRestar);
        btnRestar.setBounds(60, 210, 50, 30);

        btnMultiplicar.setBackground(new java.awt.Color(255, 0, 102));
        btnMultiplicar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnMultiplicar.setText("*");
        btnMultiplicar.setAlignmentY(0.0F);
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMultiplicar);
        btnMultiplicar.setBounds(60, 250, 50, 30);

        caja2.setBackground(new java.awt.Color(255, 255, 255));
        caja2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        caja2.setBorder(null);
        caja2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja2ActionPerformed(evt);
            }
        });
        jPanel1.add(caja2);
        caja2.setBounds(60, 100, 240, 50);

        btnDividir1.setBackground(new java.awt.Color(255, 0, 102));
        btnDividir1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnDividir1.setText("/");
        btnDividir1.setAlignmentY(0.0F);
        btnDividir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividir1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnDividir1);
        btnDividir1.setBounds(60, 290, 50, 30);

        btn0.setBackground(new java.awt.Color(255, 0, 102));
        btn0.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn0.setText("0");
        btn0.setAlignmentY(0.0F);
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn0);
        btn0.setBounds(210, 290, 40, 30);

        btn1.setBackground(new java.awt.Color(255, 0, 102));
        btn1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn1.setText("1");
        btn1.setAlignmentY(0.0F);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1);
        btn1.setBounds(160, 170, 40, 30);

        btn2.setBackground(new java.awt.Color(255, 0, 102));
        btn2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn2.setText("2");
        btn2.setAlignmentY(0.0F);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2);
        btn2.setBounds(210, 170, 40, 30);

        btn3.setBackground(new java.awt.Color(255, 0, 102));
        btn3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn3.setText("3");
        btn3.setAlignmentY(0.0F);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3);
        btn3.setBounds(260, 170, 40, 30);

        btn4.setBackground(new java.awt.Color(255, 0, 102));
        btn4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn4.setText("4");
        btn4.setAlignmentY(0.0F);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4);
        btn4.setBounds(160, 210, 40, 30);

        btn5.setBackground(new java.awt.Color(255, 0, 102));
        btn5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn5.setText("5");
        btn5.setAlignmentY(0.0F);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5);
        btn5.setBounds(210, 210, 40, 30);

        btn8.setBackground(new java.awt.Color(255, 0, 102));
        btn8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn8.setText("8");
        btn8.setAlignmentY(0.0F);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8);
        btn8.setBounds(210, 250, 40, 30);

        btn7.setBackground(new java.awt.Color(255, 0, 102));
        btn7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn7.setText("7");
        btn7.setAlignmentY(0.0F);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7);
        btn7.setBounds(160, 250, 40, 30);

        btn6.setBackground(new java.awt.Color(255, 0, 102));
        btn6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn6.setText("6");
        btn6.setAlignmentY(0.0F);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6);
        btn6.setBounds(260, 210, 40, 30);

        btn9.setBackground(new java.awt.Color(255, 0, 102));
        btn9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn9.setText("9");
        btn9.setAlignmentY(0.0F);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9);
        btn9.setBounds(260, 250, 40, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        
        caja2.setText("");
        caja3.setText("");
        
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void caja3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja3ActionPerformed

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        // TODO add your handling code here:
        int num1, num2, resultado;
        num1 = Integer.parseInt(caja1.getText());
        num2 = Integer.parseInt(caja2.getText());
        
        resultado = num1 + num2;
        
        caja3.setText("" + resultado);
        
    }//GEN-LAST:event_btnSumarActionPerformed

    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
        // TODO add your handling code here:
        int num1, num2, resultado;
        num1 = Integer.parseInt(caja1.getText());
        num2 = Integer.parseInt(caja2.getText());
        
        resultado = num1 - num2;
        
        caja3.setText("" + resultado);
        
    }//GEN-LAST:event_btnRestarActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        // TODO add your handling code here:
        int num1, num2, resultado;
        num2 = Integer.parseInt(caja2.getText());
        
        resultado = num1 * num2;
        
        caja3.setText("" + resultado);
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void caja2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja2ActionPerformed

    private void btnDividir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividir1ActionPerformed
        // TODO add your handling code here:
        int num1, num2, resultado;
        num1 = Integer.parseInt(caja1.getText());
        num2 = Integer.parseInt(caja2.getText());
        
        resultado = num1 / num2;
        
        caja3.setText("" + resultado);
    }//GEN-LAST:event_btnDividir1ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        caja2.setText(caja2.getText() + "1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        caja2.setText(caja2.getText() + "2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        caja2.setText(caja2.getText() + "3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        caja2.setText(caja2.getText() + "4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        caja2.setText(caja2.getText() + "5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        caja2.setText(caja2.getText() + "6");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        caja2.setText(caja2.getText() + "7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        caja2.setText(caja2.getText() + "8");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        caja2.setText(caja2.getText() + "9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        caja2.setText(caja2.getText() + "0");
    }//GEN-LAST:event_btn0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnDividir1;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSumar;
    private javax.swing.JTextField caja2;
    private javax.swing.JTextField caja3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
